### ISSUE TITLE
pokemonTester.py

### ISSUE THREAD

**Issue by adamclement-exe** [adamclement-exe/pokemonDashboard#11]
![image](https://user-images.githubusercontent.com/57185830/117665641-f3e6c800-b19a-11eb-8629-1a5e23210309.png)

i appreciate that this isn't a client-facing module, but can we make it close the search form after each search?

at present, if you run this, you get hundreds of search form windows loading

also, shouldn't this log if the pokemon was found?

tbh, i'm not 100% sure what this is testing :)

**Comment by JLey21** [comment]
It was just a test to see how it would interact with the GUI and is far from finished. We will add these once the GUI is complete
