### ISSUE TITLE
Manual

### ISSUE THREAD

**Issue by JLey21** [adamclement-exe/pokemonDashboard#13]
Don't forget to write the manual and upload it to Moodle

**Comment by Hiddenmaask** [comment]
ok

**Comment by Madmegsox1** [comment]
Are You China

**Comment by JLey21** [comment]
> Are You China

no.

**Comment by JLey21** [comment]
we also have to do an evaluation

https://moodle.exe-coll.ac.uk/mod/assign/view.php?id=107889

and the hand in for manual is https://moodle.exe-coll.ac.uk/mod/assign/view.php?id=107891
