### ISSUE TITLE
Pokeballs.py

### ISSUE THREAD

**Issue by adamclement-exe** [adamclement-exe/pokemonDashboard#6]
![image](https://user-images.githubusercontent.com/57185830/117648099-baf02880-b185-11eb-89fa-987ca5c444ac.png)

Can we get the info to appear on a label? - will need the GUI to be updated.  At the moment the info is printed to the console.

**Comment by Squidnugi** [comment]
yeah so that isn't finished, I do plan to make that look nice and the info come up on a gui not console. But because of this I found a missing bit of code so that's nice.
