### ISSUE TITLE
addnewpokemon.py

### ISSUE THREAD

**Issue by adamclement-exe** [adamclement-exe/pokemonDashboard#7]
![image](https://user-images.githubusercontent.com/57185830/117648455-233f0a00-b186-11eb-8139-1d69345807c2.png)

Can we have drop downs for type 1 and type 2?

**Comment by Basker12** [comment]
@adamclement-exe yes i can implement drop down menus for type 1 and type 2.

**Comment by Basker12** [comment]
I have added the two drop menus for for type 1 and type 2 :)
