### ISSUE TITLE
addnewpokemon.py

### ISSUE THREAD

**Issue by adamclement-exe** [adamclement-exe/pokemonDashboard#8]
![image](https://user-images.githubusercontent.com/57185830/117649409-63eb5300-b187-11eb-84f7-4c88839cd2f8.png)

newly added pokemon seem to be adding on the same line as the last pokemon in the csv, instead of being put on a new line.

**Comment by Basker12** [comment]
@adamclement-exe i'm gonna re-search to see if i can solve this problem.

**Comment by Basker12** [comment]
It should now create a new pokemon on the new line.
