### ISSUE TITLE
filter.py

### ISSUE THREAD

**Issue by adamclement-exe** [adamclement-exe/pokemonDashboard#9]
![image](https://user-images.githubusercontent.com/57185830/117650553-c55ff180-b188-11eb-9e88-7c2c46532b0f.png)

![image](https://user-images.githubusercontent.com/57185830/117650516-b7aa6c00-b188-11eb-9d24-48e96117eef2.png)

if you choose filters that would return zero results the code exits with an error

**Comment by UK-BreadEnjoyer** [comment]
Fixed now
